new recipe makaron penne z sosem smietanowo-serowym
pastaandpizza/recipes pull request #5
Opened 2022-04-15 16:51 UTC by DawidGardzinski

2022-05-11 14:33 UTC, boromil commented on pl-makaron-penne-z-sosem-smietanowo-serowym.md
> +4. po rozgrzaniu patelni dodajemy cebule, czosnek i dodajemy soli,
średnio gorąca/mocno gorąca?

2022-05-11 14:35 UTC, Miuosz commented on README.md
> +[Makaron](pl-makaron-penne-z-sosem-smietanowo-serowym.md)
Zamiast ogólnie `Makaron` proponowałbym `Penne z sosem śmietanowo-serowy`

2022-12-17 13:08 UTC, Icikowski requested changes

2022-12-17 13:08 UTC, Icikowski commented on pl-makaron-penne-z-sosem-smietanowo-serowym.md
> +# Makaron penne z sosem śmietanowo serowym
Dodaj frontmatter, może się niedługo przydać :)

```suggestion
---
title: "Makaron penne z sosem śmietanowo serowym"
categories: ["Makarony"]
---

# Makaron penne z sosem śmietanowo serowym
```

2023-10-07 09:18 UTC, closed without merging